export const VERSION = "0.1.3";

export const DEFAULT_PORT = 8000;
export const DEFAULT_WS_PORT = 18789;
export const DEFAULT_WEB_PORT = 3000;

export const MAX_MESSAGE_LENGTH = 100_000;
export const MAX_SESSION_NAME_LENGTH = 200;

export const CONSENT_TIMEOUT_MS = 5 * 60 * 1000; // 5 minutes

export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",

  // Sessions
  SESSION_NOT_FOUND: "SESSION_NOT_FOUND",
  SESSION_CLOSED: "SESSION_CLOSED",

  // Actions
  ACTION_NOT_FOUND: "ACTION_NOT_FOUND",
  ACTION_ALREADY_EXECUTED: "ACTION_ALREADY_EXECUTED",
  CONSENT_TIMEOUT: "CONSENT_TIMEOUT",
  CONSENT_REJECTED: "CONSENT_REJECTED",

  // Tools
  TOOL_NOT_FOUND: "TOOL_NOT_FOUND",
  TOOL_EXECUTION_FAILED: "TOOL_EXECUTION_FAILED",
  TOOL_PERMISSION_DENIED: "TOOL_PERMISSION_DENIED",

  // Surfaces
  SURFACE_NOT_FOUND: "SURFACE_NOT_FOUND",
  SURFACE_UNAVAILABLE: "SURFACE_UNAVAILABLE",

  // General
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  RATE_LIMITED: "RATE_LIMITED",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];
