import { test, expect } from '@playwright/test'

test('browser actions remain visible with page context, safe details and keyboard screenshot expansion', async ({ page }) => {
  const capturedPage = await page.context().newPage()
  await capturedPage.setViewportSize({ width: 640, height: 360 })
  await capturedPage.setContent('<html><body style="font:18px system-ui;background:#f5f8fb;padding:32px;color:#123"><h1>Jait documentation</h1><p>Getting started</p><p>Follow your agent through browser actions.</p><button>Search docs</button></body></html>')
  const screenshotPng = await capturedPage.screenshot()
  await capturedPage.close()
  await page.route('https://browser-fixture.test/page.png', (route) => route.fulfill({ contentType: 'image/png', body: screenshotPng }))
  await page.goto('/browser-activity-repro.html')
  const activities = page.getByRole('region', { name: 'Browser activity' })
  await expect(activities).toHaveCount(5)
  const navigation = activities.filter({ hasText: 'Jait documentation' })
  const running = activities.filter({ hasText: 'In progress' })
  const secret = activities.filter({ hasText: 'Private page' })
  const failed = activities.filter({ hasText: 'Failed' })
  await expect(navigation.getByText('Jait documentation')).toBeVisible()
  await expect(navigation.getByRole('link')).toHaveAttribute('href', 'https://example.com/docs')
  await navigation.getByText('Page details · 2 elements').click()
  await expect(navigation.getByText('Learn how to use Jait browser tools.')).toBeVisible()
  await expect(navigation.getByRole('list', { name: 'Page elements' })).toContainText('Getting started')
  await expect(running.getByRole('status')).toHaveText('In progress')
  await expect(running.getByText('text=Getting started', { exact: true })).toBeVisible()
  await expect(secret).toContainText('Page capture is hidden')
  await expect(page.getByText('SECRET_FIXTURE')).toHaveCount(0)
  await expect(secret.locator('details')).toHaveCount(0)
  await expect(failed.getByRole('status')).toHaveText('Failed')
  await expect(failed.getByText('Element was not found')).toBeVisible()

  const screenshot = page.getByRole('button', { name: 'Expand browser screenshot' })
  await expect(screenshot.locator('img')).toHaveJSProperty('naturalWidth', 640)
  await screenshot.focus()
  await page.keyboard.press('Enter')
  await expect(page.getByRole('dialog')).toBeVisible()
  await page.keyboard.press('Escape')
  await expect(page.getByRole('dialog')).toHaveCount(0)
  await page.getByRole('button', { name: 'Finish browser action' }).click()
  await expect(activities).toHaveCount(5)
  await expect(activities.filter({ hasText: 'https://example.com/docs/start' }).getByText('Getting started', { exact: true })).toBeVisible()
  await page.reload()
  await expect(activities.nth(0).getByText('Jait documentation')).toBeVisible()

  await navigation.getByText('Page details · 2 elements').click()
  await page.screenshot({ path: '../../.jait/browser-activity-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await expect(activities.nth(0)).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: '../../.jait/browser-activity-preview.png', fullPage: true })
})
