import { expect, test } from '@playwright/test'

for (const width of [390, 1280]) {
  test(`single queued message expands without dragging or shifting transcript at ${width}px`, async ({ page }) => {
    await page.setViewportSize({ width, height: 900 })
    await page.goto('/', { waitUntil: 'domcontentloaded' })
    await page.evaluate(() => import('/src/e2e-fixtures/queue-selection.tsx'))
    const row = page.locator('[data-queue-id="single"]')
    await expect(row).toBeVisible()
    await page.waitForTimeout(700)
    const before = await row.boundingBox()
    await row.getByText(/Queued detail 0/).click()
    await expect(row.getByRole('button', { name: 'Collapse queued message' })).toBeVisible()
    await expect(row).not.toHaveClass(/opacity-0/)
    await expect(row.getByLabel('Drag to reorder')).toHaveCount(0)
    await page.waitForTimeout(650)
    const after = await row.boundingBox()
    expect(Math.abs(after!.y - before!.y)).toBeLessThan(3)
    await row.getByRole('button', { name: 'Collapse queued message' }).click()
    await expect(row.getByRole('button', { name: 'Expand queued message' })).toBeVisible()
    await row.getByRole('button', { name: 'Edit message' }).click()
    await row.locator('textarea').fill('Updated message')
    await row.locator('textarea').press('Enter')
    await expect(row.getByText('Updated message', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: 'Add second' }).click()
    await expect(page.getByLabel('Drag to reorder', { exact: true })).toHaveCount(2)
    const second = page.locator('[data-queue-id="second"]')
    const grip = await row.getByLabel('Drag to reorder', { exact: true }).boundingBox()
    const target = await second.boundingBox()
    await page.mouse.move(grip!.x + 5, grip!.y + 5)
    await page.mouse.down()
    await page.mouse.move(target!.x + 20, target!.y + target!.height - 2, { steps: 8 })
    await page.mouse.up()
    await expect.poll(() => page.locator('[data-queue-id]').evaluateAll(rows => rows.map(row => row.getAttribute('data-queue-id')))).toEqual(['second', 'single'])
  })
}
