import type {
  AgentThread,
  AutomationPlan,
  AutomationRepo,
  CreateJaitTodoRequest,
  CreatePlanRequest,
  CreateReminderRequest,
  CreateRepoRequest,
  CreateThreadRequest,
  GenerateJaitTodosRequest,
  GeneratePlanTasksRequest,
  JaitTodo,
  PlanStatus,
  PlanTask,
  PlanTaskStatus,
  ProviderAuthStatus,
  ProviderInfo,
  ProviderLoginResult,
  ProviderLogoutResult,
  RemoteProviderInfo,
  ReminderRecord,
  ReminderSnapshot,
  ThreadActivity,
  UpdateJaitTodoRequest,
  UpdatePlanRequest,
  UpdateReminderRequest,
  UpdateRepoRequest,
  UpdateThreadRequest,
  UserSecretRecord,
} from './agents-api'
import type {
  AgentThread as SharedAgentThread,
  AutomationPlan as SharedAutomationPlan,
  AutomationRepo as SharedAutomationRepo,
  CreateJaitTodoRequest as SharedCreateJaitTodoRequest,
  CreatePlanRequest as SharedCreatePlanRequest,
  CreateReminderRequest as SharedCreateReminderRequest,
  CreateRepoRequest as SharedCreateRepoRequest,
  CreateThreadRequest as SharedCreateThreadRequest,
  GenerateJaitTodosRequest as SharedGenerateJaitTodosRequest,
  GeneratePlanTasksRequest as SharedGeneratePlanTasksRequest,
  JaitTodo as SharedJaitTodo,
  PlanStatus as SharedPlanStatus,
  PlanTask as SharedPlanTask,
  PlanTaskStatus as SharedPlanTaskStatus,
  ProviderAuthStatus as SharedProviderAuthStatus,
  ProviderInfo as SharedProviderInfo,
  ProviderLoginResult as SharedProviderLoginResult,
  ProviderLogoutResult as SharedProviderLogoutResult,
  RemoteProviderInfo as SharedRemoteProviderInfo,
  ReminderRecord as SharedReminderRecord,
  ReminderSnapshot as SharedReminderSnapshot,
  ThreadActivity as SharedThreadActivity,
  UpdateJaitTodoRequest as SharedUpdateJaitTodoRequest,
  UpdatePlanRequest as SharedUpdatePlanRequest,
  UpdateReminderRequest as SharedUpdateReminderRequest,
  UpdateRepoRequest as SharedUpdateRepoRequest,
  UpdateThreadRequest as SharedUpdateThreadRequest,
  UserSecretRecord as SharedUserSecretRecord,
} from '@jait/shared'

type IsEqual<Left, Right> =
  (<Value>() => Value extends Left ? 1 : 2) extends
    (<Value>() => Value extends Right ? 1 : 2)
    ? true
    : false

type Assert<T extends true> = T

export type AgentApiContractAssertions = [
  Assert<IsEqual<AgentThread, SharedAgentThread>>,
  Assert<IsEqual<ThreadActivity, SharedThreadActivity>>,
  Assert<IsEqual<ProviderInfo, SharedProviderInfo>>,
  Assert<IsEqual<ProviderAuthStatus, SharedProviderAuthStatus>>,
  Assert<IsEqual<ProviderLoginResult, SharedProviderLoginResult>>,
  Assert<IsEqual<ProviderLogoutResult, SharedProviderLogoutResult>>,
  Assert<IsEqual<RemoteProviderInfo, SharedRemoteProviderInfo>>,
  Assert<IsEqual<CreateThreadRequest, SharedCreateThreadRequest>>,
  Assert<IsEqual<UpdateThreadRequest, SharedUpdateThreadRequest>>,
  Assert<IsEqual<AutomationRepo, SharedAutomationRepo>>,
  Assert<IsEqual<CreateRepoRequest, SharedCreateRepoRequest>>,
  Assert<IsEqual<UpdateRepoRequest, SharedUpdateRepoRequest>>,
  Assert<IsEqual<PlanStatus, SharedPlanStatus>>,
  Assert<IsEqual<PlanTaskStatus, SharedPlanTaskStatus>>,
  Assert<IsEqual<PlanTask, SharedPlanTask>>,
  Assert<IsEqual<AutomationPlan, SharedAutomationPlan>>,
  Assert<IsEqual<CreatePlanRequest, SharedCreatePlanRequest>>,
  Assert<IsEqual<UpdatePlanRequest, SharedUpdatePlanRequest>>,
  Assert<IsEqual<GeneratePlanTasksRequest, SharedGeneratePlanTasksRequest>>,
  Assert<IsEqual<JaitTodo, SharedJaitTodo>>,
  Assert<IsEqual<CreateJaitTodoRequest, SharedCreateJaitTodoRequest>>,
  Assert<IsEqual<UpdateJaitTodoRequest, SharedUpdateJaitTodoRequest>>,
  Assert<IsEqual<GenerateJaitTodosRequest, SharedGenerateJaitTodosRequest>>,
  Assert<IsEqual<ReminderRecord, SharedReminderRecord>>,
  Assert<IsEqual<ReminderSnapshot, SharedReminderSnapshot>>,
  Assert<IsEqual<CreateReminderRequest, SharedCreateReminderRequest>>,
  Assert<IsEqual<UpdateReminderRequest, SharedUpdateReminderRequest>>,
  Assert<IsEqual<UserSecretRecord, SharedUserSecretRecord>>,
]
