import Fastify from "fastify";
import { afterEach, describe, expect, it } from "vitest";
import { loadConfig } from "../config.js";
import { migrateDatabase, openDatabase } from "../db/index.js";
import type { ProviderEvent, CliProviderAdapter, ProviderId, ProviderInfo, ProviderSession, RuntimeMode, StartSessionOptions } from "../providers/contracts.js";
import { ProviderRegistry } from "../providers/registry.js";
import { signAuthToken } from "../security/http-auth.js";
import { registerPlanRoutes } from "./plans.js";
import { PlanService } from "../services/plans.js";
import { RepositoryService } from "../services/repositories.js";

class StubCliProvider implements CliProviderAdapter {
  readonly id: ProviderId = "codex";
  readonly info: ProviderInfo = {
    id: "codex",
    name: "Stub Codex",
    description: "Test provider",
    available: true,
    modes: ["full-access", "supervised"],
  };

  private listeners = new Set<(event: ProviderEvent) => void>();
  public lastStartOptions: StartSessionOptions | null = null;
  public lastMessage: string | null = null;

  async checkAvailability(): Promise<boolean> {
    return true;
  }

  async startSession(options: StartSessionOptions): Promise<ProviderSession> {
    this.lastStartOptions = options;
    return {
      id: "stub-session",
      providerId: "codex",
      threadId: options.threadId,
      status: "running",
      runtimeMode: options.mode,
      startedAt: new Date().toISOString(),
    };
  }

  async sendTurn(sessionId: string, message: string): Promise<void> {
    this.lastMessage = message;
    for (const listener of this.listeners) {
      listener({
        type: "message",
        sessionId,
        role: "assistant",
        content: JSON.stringify([{ title: "Use selected provider", description: "Generated by CLI provider" }]),
      });
      listener({ type: "turn.completed", sessionId });
    }
  }

  async interruptTurn(): Promise<void> {
    return;
  }

  async respondToApproval(): Promise<void> {
    return;
  }

  async stopSession(): Promise<void> {
    return;
  }

  onEvent(listener: (event: ProviderEvent) => void): () => void {
    this.listeners.add(listener);
    return () => {
      this.listeners.delete(listener);
    };
  }
}

async function authHeader(jwtSecret: string, userId = "test-user") {
  const token = await signAuthToken({ id: userId, username: `${userId}-name` }, jwtSecret);
  return { authorization: `Bearer ${token}` };
}

describe("plan generation provider selection", () => {
  let sqlite: ReturnType<typeof openDatabase>["sqlite"] | null = null;

  afterEach(() => {
    sqlite?.close();
    sqlite = null;
  });

  it("uses the explicitly selected CLI provider and model", async () => {
    const opened = await openDatabase(":memory:");
    sqlite = opened.sqlite;
    migrateDatabase(sqlite);

    const app = Fastify({ logger: false });
    const config = { ...loadConfig(), jwtSecret: "test-jwt-secret", logLevel: "silent" };
    const repoService = new RepositoryService(opened.db);
    const planService = new PlanService(opened.db);
    const providerRegistry = new ProviderRegistry();
    const stubProvider = new StubCliProvider();
    providerRegistry.register(stubProvider);

    registerPlanRoutes(app, config, {
      planService,
      repoService,
      providerRegistry,
    });

    const repo = repoService.create({
      userId: "test-user",
      name: "repo",
      localPath: process.cwd(),
    });
    const plan = planService.create({
      repoId: repo.id,
      userId: "test-user",
      title: "Plan",
      tasks: [],
    });

    const res = await app.inject({
      method: "POST",
      url: `/api/plans/${plan.id}/generate`,
      headers: await authHeader(config.jwtSecret),
      payload: {
        prompt: "Generate a todo",
        provider: "codex",
        model: "gpt-5-codex",
      },
    });

    expect(res.statusCode).toBe(200);
    expect(stubProvider.lastStartOptions?.workingDirectory).toBe(repo.localPath);
    expect(stubProvider.lastStartOptions?.model).toBe("gpt-5-codex");
    expect(stubProvider.lastMessage).toContain("Output ONLY the JSON array");
    expect(stubProvider.lastMessage).not.toContain("skillCandidate");
    expect(stubProvider.lastMessage).not.toContain("reusable skill");

    const body = res.json() as { generated: number; plan: { tasks: Array<{ title: string; description: string }> } };
    expect(body.generated).toBe(1);
    expect(body.plan.tasks).toEqual([
      expect.objectContaining({
        title: "Use selected provider",
        description: "Generated by CLI provider",
      }),
    ]);

    await app.close();
  });
});
